package pl.dev4lazy.waste;

import java.util.ArrayList;


public class CsvLineToStoreWasteInfoDecoder implements Decoder<ArrayList<String>,StoreWasteInfo>{

    @Override
    public StoreWasteInfo decode(ArrayList<String> parsedCsvLine) {
        parsedCsvLine = CsvUtils.replaceCommasToPoints( parsedCsvLine );
        StoreWasteInfo storeWasteInfo = new StoreWasteInfo.StoreWasteInfoBuilder()
                .withStore(parsedCsvLine.get(0))
                .withName(parsedCsvLine.get(1))
                .withRegion(parsedCsvLine.get(2))
                .with_17_09_04(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(3)))
                .with_15_01_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(4)))
                .with_15_01_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(5)))
                .with_15_01_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(6)))
                .with_17_04_05(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(7)))
                .with_16_02_13_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(8)))
                .with_16_02_14(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(9)))
                .with_16_02_16(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(10)))
                .with_07_04_80_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(11)))
                .with_16_06_05(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(12)))
                .with_16_03_06(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(13)))
                .with_16_03_05_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(14)))
                .with_07_04_81(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(15)))
                .with_16_06_04(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(16)))
                .with_02_01_08_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(17)))
                .with_20_03_07(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(18)))
                .with_20_01_36(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(19)))
                .with_17_09_03_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(20)))
                .with_13_02_08_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(21)))
                .with_17_01_07(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(22)))
                .with_02_01_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(23)))
                .with_03_01_05(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(24)))
                .with_17_01_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(25)))
                .with_17_01_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(26)))
                .with_17_01_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(27)))
                .with_15_01_11_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(28)))
                .with_15_01_10_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(29)))
                .with_15_01_06(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(30)))
                .with_17_04_07(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(31)))
                .with_16_03_03_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(32)))
                .with_17_02_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(33)))
                .with_08_01_12(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(34)))
                .with_15_02_02_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(35)))
                .with_16_03_04(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(36)))
                .with_16_02_11_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(37)))
                .with_15_02_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(38)))
                .with_08_01_11_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(39)))
                .with_20_02_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(40)))
                .with_13_07_03_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(41)))
                .with_17_06_04(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(42)))
                .with_16_01_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(43)))
                .with_16_01_19(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(44)))
                .with_20_01_21_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(45)))
                .with_13_02_05_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(46)))
                .with_20_03_99(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(47)))
                .with_07_04_04_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(48)))
                .with_08_03_18(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(49)))
                .with_15_01_04(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(50)))
                .with_17_04_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(51)))
                .with_17_02_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(52)))
                .with_16_06_01_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(53)))
                .with_13_03_07_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(54)))
                .with_07_02_13(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(55)))
                .with_20_01_29_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(56)))
                .with_17_04_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(57)))
                .with_20_01_34(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(58)))
                .with_17_03_80(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(59)))
                .with_15_01_05(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(60)))
                .with_15_01_07(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(61)))
                .with_20_01_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(62)))
                .with_20_01_38(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(63)))
                .with_16_02_15_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(64)))
                .with_03_01_04_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(65)))
                .with_14_06_03_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(66)))
                .with_20_01_35_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(67)))
                .with_20_02_03(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(68)))
                .with_19_12_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(69)))
                .with_08_04_10(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(70)))
                .with_08_04_09_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(71)))
                .with_20_03_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(72)))
                .with_15_01_09(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(73)))
                .with_20_01_39(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(74)))
                .with_06_13_01_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(75)))
                .with_17_01_82(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(76)))
                .with_17_02_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(77)))
                .with_20_01_19_aster(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(78)))
                .with_17_08_02(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(79)))
                .with_20_01_01(CsvUtils.getDoubleOrNullFromString(parsedCsvLine.get(80)))
                .build();
        return storeWasteInfo;
    }

}
